name: Tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]

        steps:
          - name: Checkout branch
            uses: actions/checkout@v3

          - name: Set up PDM
            uses: pdm-project/setup-pdm@main
            with:
              python-version: ${{ matrix.python-version }}
              cache: true

          - name: Setup ssh key
            uses: webfactory/ssh-agent@v0.5.1
            with:
              ssh-private-key: ${{ secrets.SSH_KEY }}

          - name: Install dependencies
            run: pdm install

          - name: Run Tests
            run: pdm test
